[project]
name = "tutu"
version = "0.1.0"
description = "Task management system for Claude Code sessions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=2.0.41",
    "typer>=0.16.0",
]

[project.scripts]
tutu = "tutu.cli:main"
